pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                checkout scm
            }
        }
        stage('Test') {
            steps {
                /* `make check` returns non-zero on test failures,
                * using `true` to allow the Pipeline to continue nonetheless
                */
                sh 'python -m pytest src/test_primes.py' 
                
            }
        }
    }
}
